name: Update Playlist with Cookie

on:
  schedule:
    - cron: '30 18 * * *'   # Runs daily at 00:00 IST
  workflow_dispatch:

jobs:
  update-cookie:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requests module
        run: pip install requests

      - name: Run fetch.py
        run: python fetch.py

      - name: Commit & push updates
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add playlist.php fetch.json
          git commit -m "🔄 Auto-update cookie and playlist (Python)" || echo "No changes"
          git push
