name: Auto Update Playlist and Cookie

on:
  workflow_dispatch:     # Manual trigger available
  schedule:
    - cron: '30 18 * * *'  # Runs daily at 00:00:00 IST (18:30 UTC)

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: pip install requests pytz

    - name: Run fetch.py to update playlist.php and fetch.json
      run: python fetch.py

    - name: Commit and push updates
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add playlist.php fetch.json
        git commit -m "🔄 Auto-update playlist.php and fetch.json (Python)" || echo "No changes to commit"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        git push origin HEAD:main
